#SAMPLE CONFIG FILE
---
## This info could be retrieved by YANG instead of in config ##
router:
  ip: "10.30.111.168"
  port: 1234
  username: "cisco"
  password: "cisco123!"
###############################################################

sensor-groups:
  - sensor-group-id: "SG"
    sensor-paths:
      - "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-xr/interface"

collectors:
  - subscription:
      subscription-id: "Primary-Sub"
      interval: 30000
    destination-group:
      ip: "10.30.111.165"
      port: 1234
      destination-id: "Primary-DG"
      encoding: "self-describing-gpb"
      protocol: "grpc"
  - subscription:
      subscription-id: "Secondary-Sub"
      interval: 30000
    destination-group:
      ip: "5.6.7.8"
      port: 1234
      destination-id: "Secondary-DG"
      encoding: "self-describing-gpb"
      protocol: "grpc"
