# This is a sample config file for the automated telemetry configuration changing script
# It must be named config.yaml for the script to function
# It must conform to the schema defined in src/schema.json
# It will be mounted into the docker container at runtime
# It defines the characteristics of the router, the telemetry collector and its backups
---

### ROUTER CHARACTERISTICS ###
router:
  ip: "127.0.0.1"         # IP address of the router (Use 127.0.0.1 if running on local machine)
  port: 57777             # Port enabled for grpc communication
  username: "cisco"       # Username of router
  password: "cisco123"    # Password of router
  tls: true               # Encrypt configuration messages from xr-collector-health-monitor
                          # Must have grpc configured with tls and /misc/config/grpc/ems.pem copied into mounted config directory

### SENSOR GROUPS FOR TELEMETRY ###
sensor-groups:
  - sensor-group-id: "Sample-Sensor-Group-Name"                                                     # Name of a sensor group
    sensor-paths:
      - "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-xr/interface"                            # List of sensor paths in sensor group
      - "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/data-rate"
  - sensor-group-id: "Sample-Sensor-Group-Name-2"                                                   # Name of a second sensor group
    sensor-paths:
      - Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary                                # Another list of sensor paths in the second sensor group

### SERIES OF COLLECTORS ###

# The script will automatically configure the router to send telemetry data to the 
# the highest-priority active collector. The order of collectors in the list is 
# the order of their priority

collectors:
  - destination-group:
      ip: "4.5.6.7"                       # IP address of the primary collector
      port: 57777                         # Port the primary collector is listening on
      destination-id: "First-Collector"   # Name of the primary collector
      encoding: "self-describing-gpb"     # Encoding for the primary collector
      protocol: "grpc"                    # Protocol for the primary collector
      tls: false                          # Do not encrypt telemetry data with tls
    subscription:
      subscription-id: "Subscription-1"   # Name of the subscription
      interval: 30000                     # Time interval to send the telemetry data

  - destination-group:
      ip: "7.6.5.4"                          # IP address of the secondary collector
      port: 57777                            # Port the secondary collector is listening on
      destination-id: "Second-Collector"     # Name of the secondary collector
      encoding: "self-describing-gpb"        # Encoding for the primary collector
      protocol: "grpc"                       # Protocol for the primary collector
      tls: true                              # Encrypt telemetry data with tls. CA Certificate must be copied into /misc/config/grpc/dialout/dialout.pem in advance
      tls-hostname: "hostname.com"           # Optional parameter to define the tls-hostname when tls is true
    subscription:
      subscription-id: "Subscription-2"      # Name of the subscription
      interval: 30000                        # Time interval to send the telemetry data

# Further backup collectors can be added if necessary