name: Docker Image and RPM Build

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        # push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/xr-collector-health-monitor:${{ github.event.inputs.version}}
        outputs: type=docker,dest=xr-collector-health-monitor.tar

    - name: Debugging
      run: |
        ls
        cd package
        ls

    - name: Package as RPM
      run: |
        cd package
        chmod 777 appmgr_build
        ./appmgr_build -b ./build.yaml

    - name: Debugging 2
      run: |
        ls
        cd package
        ls

    - name: Upload RPM
      uses: actions/upload-artifact@v2
      with:
        name: RPM-${{ github.event.inputs.version }}
        path: package/RPMS/x86_64
