name: Image and RPM Build

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/xr-collector-health-monitor:${{ github.event.inputs.version }} .
        docker save ${{ secrets.DOCKER_HUB_USERNAME }}/xr-collector-health-monitor:${{ github.event.inputs.version }} > xr-collector-health-monitor.tar
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/xr-collector-health-monitor:${{ github.event.inputs.version }}

    - name: Package as RPM - eXR
      run: |
        cd package
        chmod 777 appmgr_build
        chmod 777 docker/build_rpm.sh
        sed -i "s/{VERSION}/${{ github.event.inputs.version }}/" build.yaml
        ./appmgr_build -b ./build.yaml

    - name: Upload RPM - eXR
      uses: actions/upload-artifact@v2
      with:
        name: xr-collector-health-monitor-${{ github.event.inputs.version }}-eXR_7.3.1.x86_64.rpm
        path: package/RPMS/x86_64/xr-collector-health-monitor-${{ github.event.inputs.version }}-eXR_7.3.1.x86_64.rpm

    - name: Package as RPM - ThinXR
      run: |
        cd package
        chmod 777 appmgr_build
        chmod 777 docker/build_rpm.sh
        sed -i "s/eXR_7.3.1/ThinXR_7.3.15/" build.yaml
        ./appmgr_build -b ./build.yaml

    - name: Upload RPM - ThinXR
      uses: actions/upload-artifact@v2
      with:
        name: xr-collector-health-monitor-${{ github.event.inputs.version }}-ThinXR_7.3.15.x86_64.rpm
        path: package/RPMS/x86_64/xr-collector-health-monitor-${{ github.event.inputs.version }}-ThinXR_7.3.15.x86_64.rpm

    - name: Push RPMS
      run: |
        sudo mv package/RPMS/x86_64/xr-collector-health-monitor-${{ github.event.inputs.version }}-eXR_7.3.1.x86_64.rpm RPMS
        sudo mv package/RPMS/x86_64/xr-collector-health-monitor-${{ github.event.inputs.version }}-ThinXR_7.3.15.x86_64.rpm RPMS
        git config --global user.name 'Adam Horton'
        git config --global user.email 'adhorton@cisco.com'
        git add RPMS
        git commit -m "Automated Build"
        git push
